name: opentelemetry
version: 0.15.1
description: A framework for collecting traces from applications.
homepage: https://github.com/Workiva/opentelemetry-dart
environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  collection: ^1.0.0
  fixnum: '>=0.10.0 <2.0.0'
  http: '>=0.12.0+2 <0.14.0'
  logging: '>=0.11.4 <2.0.0'
  protobuf: '>=1.1.0 <3.0.0'
  quiver: '>=2.1.5 <4.0.0'
  test_coverage: ^0.4.2
  
dependency_overrides:
  meta: 1.6.0

dev_dependencies:
  glob: ^1.1.7
  mockito: ^4.0.7
  test: any
  workiva_analysis_options: ^1.2.2
